# Generated by Django 5.1 on 2024-08-29 15:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=ckeditor.fields.RichTextField(default='default_value'),
            preserve_default=False,
        ),
    ]
