# Generated by Django 5.1 on 2024-08-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_tags'),
    ]

    operations = [
    ]
