# Generated by Django 5.1 on 2024-09-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_address_address_details_address_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_name',
            field=models.CharField(default='Unnamed', max_length=100),
            preserve_default=False,
        ),
    ]
