# Generated by Django 5.1 on 2024-09-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_name',
        ),
        migrations.AddField(
            model_name='address',
            name='address_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
