# Generated by Django 5.1 on 2024-09-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_order_address_name_address_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
