# Generated by Django 5.1 on 2024-09-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_address_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='location_lat',
            field=models.DecimalField(decimal_places=18, default='', max_digits=22),
        ),
        migrations.AlterField(
            model_name='address',
            name='location_long',
            field=models.DecimalField(decimal_places=18, default='', max_digits=22),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
