# Generated by Django 5.1 on 2024-08-25 14:34

import ckeditor.fields
import datetime
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('stock', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product_photo', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('product_photo_1', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Natural Ingredients', 'Natural Ingredients'), ('Organic', 'Organic'), ('Raw Honey', 'Raw Honey'), ('Freshly Harvested', 'Freshly Harvested'), ('Unprocessed', 'Unprocessed'), ('Premium Quality', 'Premium Quality'), ('No Additives', 'No Additives')], max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('review_text', models.TextField()),
                ('review_date', models.DateField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('verified_purchase', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
        ),
    ]
